### ISSUE TITLE
support HashLink?

### ISSUE THREAD

**Issue by sonygod** [ianharrigan/hxWebSockets#1]
support HashLink?

current it's seem not work on HashLink

@ianharrigan

**Comment by ianharrigan** [comment]
Good point, ill give it a try.

**Comment by sonygod** [comment]
please consider use var loop = Loop.getDefault(); as Main Loop.

**Comment by ianharrigan** [comment]
i havent managed to try hashlink as i cant get it to work... however, i have added some code in the git version that uses `MainLoop`... im not 100% sure im using correctly as ive never used it before... but let me know if it works.

**Comment by sonygod** [comment]
I 'll try ,thank you .

**Comment by sonygod** [comment]
improve performance  .can  use many threads 

        // MainLoop.add(function() {
                
            //      tick();
            
            // });
    

        //to 
            MainLoop.addThread(function(){
    while (true) {
                var continueLoop = tick();
                if (continueLoop == false) {
                    break;
                }

                Sys.sleep(sleepAmount);
            }
                
            });

**Comment by sonygod** [comment]
current  Hashlink  has a bug .

https://github.com/HaxeFoundation/haxe/issues/8699

**Comment by sonygod** [comment]
hashlink 1.11.0 fixed this bug , right now everything seems ok!
