### ISSUE TITLE
Pass HTTP cookies 

### ISSUE THREAD

**Issue by Tezar** [ianharrigan/hxWebSockets#11]
Currently there is no nice way to include cookies in supported targets. Extending class seems cumbersome since requests are fired as soon as instance is created, so one needs to pass cookies directly to constructor.

My current workaround consists of child class with modified constructor and sendHttpRequest to inject cookies as needed. Not exactly clean solution. Separating instantiation and actual connecting would be helpful in this case, but that would mean API breakage, which is suboptimal. 
Maybe add optional parameter connect=true and refactor rest? 

Would provide PR with connect + cookies but since its substantial alternation, I would like to know if this is viable path or you have something different in mind.

**Comment by ianharrigan** [comment]
Sounds good to me... I had no plans on adding cookie support, but it sounds like it may be very useful, so a PR sounds like it might be ideal. We can always discuss the finer details in the context of the PR...

I look forward to it!

Cheers,
Ian

**Comment by ianharrigan** [comment]
Just to confirm - this is fixed now with the merge above, right?

**Comment by Tezar** [comment]
Yup, it should be. Sorry, I forgot to put magic word into PR description to close this automatically.

**Comment by ianharrigan** [comment]
Cool - thanks!
