### ISSUE TITLE
support c# target for unity as client?

### ISSUE THREAD

**Issue by sonygod** [ianharrigan/hxWebSockets#13]
support c# target for unity as a client?

Is there any plan?

**Comment by ianharrigan** [comment]
So the standard (sys) web socket client doenst work on c#?? Are there issues with standard haxe sockets on hxcs?? :/

**Comment by sonygod** [comment]
No , can't  work on cs target as client

**Comment by ianharrigan** [comment]
the hxcs client seems to work for me:

![image](https://user-images.githubusercontent.com/3024242/67677129-85a92e80-f983-11e9-902d-b8ee3ac1b00e.png)

im using this server: 

* https://github.com/ianharrigan/hxWebSockets/tree/master/Examples/node-server-not-hxws

and this client: 

* https://github.com/ianharrigan/hxWebSockets/tree/master/Examples/sys-client

and haxe4.

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/67729423-058ad380-fa2c-11e9-8851-2745665eb2ef.png)

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/67729489-41be3400-fa2c-11e9-9d1d-f31eaeb2834c.png)

**Comment by sonygod** [comment]
https://github.com/HaxeFoundation/haxe/issues/8904

haxe error.

**Comment by sonygod** [comment]
it's seem only work for localhost or 127.0.0.1?

try to  ws://78.141.204.113:9001?

@ianharrigan

**Comment by sonygod** [comment]
I‘m sure it does not support unity , only support stand .net application 

   	
	SocketException: 不知道这样的主机。

	System.Net.Dns.hostent_to_IPHostEntry (System.String h_name, System.String[] h_aliases, System.String[] h_addrlist)
	System.Net.Dns.GetHostByAddressFromString (System.String address, Boolean parse)
	System.Net.Dns.GetHostEntry (System.Net.IPAddress address)
	System.Net.Dns.GetHostEntry (System.String hostNameOrAddress)
	sys.net.Host.__hx_ctor_sys_net_Host (sys.net.Host __hx_this, System.String name) (at C://HaxeToolkit//haxe//std//cs//_std//sys//net//Host.hx:48)
	sys.net.Host..ctor (System.String name) (at C://HaxeToolkit//haxe//std//cs//_std//sys//net//Host.hx:46)
	hx.ws.WebSocket.__hx_ctor_hx_ws_WebSocket (hx.ws.WebSocket __hx_this, System.String uri) (at D://Downloads//hxWebSockets-master//hxWebSockets-master//Examples//sys-client//src//hx//ws//WebSocket.hx:152)
	hx.ws.WebSocket..ctor (System.String uri) (at D://Downloads//hxWebSockets-master//hxWebSockets-master//Examples//sys-client//src//hx//ws//WebSocket.hx:137)
	haxe.root.Main.main () (at D://Downloads//hxWebSockets-master//hxWebSockets-master//Examples//sys-client//src//Main.hx:9)


![image](https://user-images.githubusercontent.com/748320/67821592-82837f00-faf8-11e9-8cf2-ad4a8f8a8800.png)


![image](https://user-images.githubusercontent.com/748320/67821615-96c77c00-faf8-11e9-831b-a1ce9717c004.png)

**Comment by sonygod** [comment]
fixed by this answer

https://answers.unity.com/questions/1004969/local-ip-adress-in-unet.html

**Comment by sonygod** [comment]
Host.hx
    
     public function new(name:String):Void {
            trace("host name=" + name);
            host = name;
            // hostEntry =Dns.GetHostByAddress(name);//will throw no-such-host-is-known-socket-connection
            // for (i in 0...hostEntry.AddressList.Length) {
            // 	if (hostEntry.AddressList[i].AddressFamily == InterNetwork) {
            // 		ipAddress = hostEntry.AddressList[i];
            // 		break;
            // 	}
            // }

            var ips = Dns.GetHostAddresses(name);
            ipAddress = ips[0];
        }
