### ISSUE TITLE
support IOS

### ISSUE THREAD

**Issue by sonygod** [ianharrigan/hxWebSockets#14]
when target to ios from unity ,it's seem not work .

I'm trying to debug and found out why not work .

mark.

**Comment by gepatto** [comment]
I'm having trouble with ios too.
I also tried using the daltoniam/Starscream library and tried just using sys.net.socket in Haxe 4.

**Comment by sonygod** [comment]
well ,I'll report here if I found the solutions.

**Comment by sonygod** [comment]
@gepatto 

I found here is wrong

    	var ws:WebSocket = Thread.readMessage(true);

**Comment by sonygod** [comment]
@ianharrigan  any idea?

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/68173236-58790380-ffb5-11e9-876c-6dffb46f8c50.png)

fixed by use MainLoop.addThread  to replace Thread.readMessage


@ianharrigan  @gepatto

**Comment by ianharrigan** [comment]
OK, great - can you get the latest from git and make sure it works? If it does, then ill make a haxelib release.

Thanks!
Ian

**Comment by ianharrigan** [comment]
This is the commit fyi: https://github.com/ianharrigan/hxWebSockets/commit/57df647e8e3861b9d05e049fb14e9ffc2beaac16

**Comment by sonygod** [comment]
sure
