### ISSUE TITLE
Client mode fails on server adhering to specs

### ISSUE THREAD

**Issue by Tezar** [ianharrigan/hxWebSockets#18]
According to specs mentioned even in the comment, when sending data posing as a client, one should ensure that data is masked. 
The code is there, but it's not being properly set. Peers doesn't really seem to follow guidelines and usually happily accepts unmasked data, but I have experienced problems with that in the wild.

https://github.com/ianharrigan/hxWebSockets/blob/99449905bbff96e04f457cb604d3c0b51ea7becd/hx/ws/WebSocketCommon.hx#L176

I can make pull request with exposed `clientMode:Bool` either defaulting as true (assuming that's most common scenario, but it's BC) or false (no BC, fixable when serverside drops  connections)

**Comment by ianharrigan** [comment]
Right, if the spec defines it the it should like it makes sense to make that the default with the option to override it if needed - i think, what do you think? What do you think would be the most sensible default?

**Comment by Tezar** [comment]
Well, it really depends what is the most common use case, so it could work out of the box for most people. Given the lack of communication from others here, we can only guess. But for me it's client and given the client/server server nature, it won't be so bold to assume that client will be used more often. 

What about making `isClient:bool` public on WebSocketCommon, defaulting to true, and in constructor for Handler setting it to false? I am not actually using server side, but I assume handler must be used, so it could be solution without BC.
