### ISSUE TITLE
Swap .hxproj with .hxml

### ISSUE THREAD

**Issue by aBARICHELLO** [ianharrigan/hxWebSockets#22]
I noticed that you are using what appears to be a flash develop specific build file, how about changing to a hxproj that is more generic and can be used with any library.

**Comment by ianharrigan** [comment]
Yeah, its a fair point. :)

**Comment by aBARICHELLO** [comment]
Nice, I'll try forking this and resolving this issue and #17

**Comment by aBARICHELLO** [comment]
Are the batchscripts really necessary? Haxe is multiplatform, it would be more helpfull to have it documented instead

**Comment by aBARICHELLO** [comment]
Thanks for the merge! I'll send more changes that I found useful while working on my projects.
