### ISSUE TITLE
Hashlink Server - New handler added every tick

### ISSUE THREAD

**Issue by cmcgdd** [ianharrigan/hxWebSockets#25]
Haven't tested in other targets, so only confirmed on hashlink.

`tick()` adds a new handler every time it runs, which grows `_handlers` rapidly and eventually slows everything down. After a few hours it can take 30+ seconds for a new (real) client to connect. 

This can be reproduced with the example server from the readme.

**Comment by ianharrigan** [comment]
Oh... good to know, ill check it out

**Comment by ianharrigan** [comment]
Ok, that should be fixed now - seems sockets in HL dont behave the same as other sys targets

Thanks for the heads up

Ian

**Comment by ianharrigan** [comment]
(if thats working for you, can you close the issue?)

**Comment by cmcgdd** [comment]
That's fixed it, thanks for the fast response!
