### ISSUE TITLE
Hashlink Client - Unhandled exception when server process ends without closing sockets

### ISSUE THREAD

**Issue by cmcgdd** [ianharrigan/hxWebSockets#26]
Only tested with hashlink server and client.

When the hl server quits with active connections, the next message sent by the client causes a crash in `WebSocketCommon.writeBytes()` with the error `Can't cast haxe.io.Eof to String`

The crash itself is caused by the debug log message `Log.debug(e, id);`, since `e` is a dynamic value currently equal to `haxe.io.Eof`, and can't be cast to a string for logging.

For now I've added a workaround in my own client code that wraps `socket.send(data)` in a try/catch and calls `onerror` from there like this:

```
try {
    socket.send(data);
} catch (e) {
    socket.onerror("Server disconnected unexpectedly");
}
```

**Comment by cmcgdd** [comment]
Decided to take a second during my lunch break to fix it

**Comment by ianharrigan** [comment]
Thanks for the fix!
