### ISSUE TITLE
Unable to retrieve WebSocket close codes from closed connection

### ISSUE THREAD

**Issue by FurretDev** [ianharrigan/hxWebSockets#40]
I have been attempting to retrieve the close codes from a closed WebSocket connection for the past few hours, but I have not been successful. I tried implementing code to retrieve the close codes, but it did not work. Does anyone have any insights or suggestions on how to retrieve the close code properly?

As an example, I have attempted to use the following code from WebSocketCommon.hx to retrieve the close code:
```
var b1 = _buffer.readByte();
var b2 = _buffer.readByte();
var code = (b1<<8) + (b2);
```

However, this code did not yield the expected close code. Any help on this matter would be greatly appreciated.

**Comment by FurretDev** [comment]
Hey, just wanted to give a quick update that I was able to retrieve the error message as a string (i.e "Authentication failed") instead of just the close code number. Although I'm happy with this result, I still would like to be able to retrieve the close code number for further analysis.

If anyone has any suggestions on how to achieve this, I'd be grateful for any help!

Thanks.

**Comment by ianharrigan** [comment]
Sorry, late reply - how did you get the error message? Maybe that will give hints on how to get the error code? Do you have a working example i can play with?

**Comment by ianharrigan** [comment]
gotcha, thanks for theinfo.

out of curiosity, any particular reason for switching to haxe-ws (wonder if this fork has broken something).

Cheers,
Ian

**Comment by FurretDev** [comment]
> gotcha, thanks for theinfo.
> 
> out of curiosity, any particular reason for switching to haxe-ws (wonder if this fork has broken something).
> 
> Cheers, Ian

it works better with one of my libraries i'm doing (in particular hxdiscord), but in general your library isn't broken as such
(one of the issues i had with this library is that when the connection has been closed too many times, it gives an error saying "Fatal error in GC. Too many threads", at least that happens on neko)

**Comment by FurretDev** [comment]
> > gotcha, thanks for theinfo.
> > out of curiosity, any particular reason for switching to haxe-ws (wonder if this fork has broken something).
> > Cheers, Ian
> 
> it works better with one of my libraries i'm doing (in particular hxdiscord), but in general your library isn't broken as such (one of the issues i had with this library is that when the connection has been closed too many times, it gives an error saying "Fatal error in GC. Too many threads", at least that happens on neko)

forget about this, this was some issue on my side 😭
