### ISSUE TITLE
Extend length of websocket key 

### ISSUE THREAD

**Issue by Tezar** [ianharrigan/hxWebSockets#9]
During testing against real world servers I got problem with one endpoint (strangely other endpoints handled by same server works fine). It dropped connection with HTTP 400
The problem originates in the length of websocket key, it seems that RFC requires it to be exactly 16 bytes (and random).

While random part isn't so necessary, the length seems to be issue for now.

Extending key in my local source fixes the problem.

https://softwareengineering.stackexchange.com/a/393148

I could get around to make PR for random generator if you want. Making one just for fixed key with correct length seems overkill.

**Comment by ianharrigan** [comment]
PR sounds great :)
